data_dir: /Users/tsukuba-yuuki-uehara/Desktop/kaggle/kaggle-child-mind-institute-detect-sleep-states/data
processed_dir: /Users/tsukuba-yuuki-uehara/Desktop/kaggle/kaggle-child-mind-institute-detect-sleep-states/processed_data
output_dir: /Users/tsukuba-yuuki-uehara/Desktop/kaggle/kaggle-child-mind-institute-detect-sleep-states/output
