data_dir: /home/yuuki/Desktop/competitions/kaggle/kaggle-child-mind-institute-detect-sleep-states/data
processed_dir: /home/yuuki/Desktop/competitions/kaggle/kaggle-child-mind-institute-detect-sleep-states/processed_data
output_dir: /home/yuuki/Desktop/competitions/kaggle/kaggle-child-mind-institute-detect-sleep-states/output
sub_dir: ./