data_dir: /root/aicom/kagglep/competitions/child-mind-institute-detect-sleep-states
processed_dir: /root/aicom/kagglep/kernels/yinhaojie/cmi-714/kaggle-child-mind-institute-detect-sleep-states/data/processed_data
output_dir: /root/aicom/kagglep/kernels/yinhaojie/cmi-714/kaggle-child-mind-institute-detect-sleep-states/output
model_dir: /root/aicom/kagglep/kernels/yinhaojie/cmi-714/kaggle-child-mind-institute-detect-sleep-states/output/model
sub_dir: ./