# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: inference
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local
  - model: unet1d

exp_name: dummy
phase: test
weight_path: null

seed: 42
duration: 4991
batch_size: 32
num_workers: 2

# Dataset
n_fft: 126
hop_length: 3

# post_process
post_process:
  score_th: 0.05
  distance: 1666

# label
labels:
  - 'awake'
  - "event_onset"
  - "event_wakeup"

# feature
features:
  - "anglez"
  - "enmo"
  # - "month_sin"
  # - "month_cos"
  - "hour_sin"
  - "hour_cos"
  # - "minute_sin"
  # - "minute_cos"