# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: inference
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local
  - model: unet1d

exp_name: dummy
weight_path: null

seed: 42
duration: 1024
batch_size: 32
num_workers: 2

# post_process
post_process:
  score_th: 0.5

# label
labels:
  - "event_onset"
  - "event_wakeup"

# feature
features:
  - "anglez"
  - "enmo"
  - "month_sin"
  - "month_cos"
  - "hour_sin"
  - "hour_cos"
  - "minute_sin"
  - "minute_cos"