# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local
  - model: unet1d
  - split: fold_0

seed: 42
exp_name: dummy
duration: 4991 # duration // hop_length + 1が32の倍数になるように調整

# training
epoch: 5
batch_size: 64
num_workers: 24
use_amp: true
debug: false
gradient_clip_val: 1.0
accumulate_grad_batches: 1
monitor: val_score
monitor_mode: max
check_val_every_n_epoch: 1

# Dataset
offset: 10
sigma: 10
bg_sampling_rate: 0.3
n_fft: 126
hop_length: 3

# post_process
post_process:
  score_th: 0.05
  distance: 1666

# label
labels:
  - 'awake'
  - "event_onset"
  - "event_wakeup"

# feature
features:
  - "anglez"
  - "enmo"
  # - "month_sin"
  # - "month_cos"
  - "hour_sin"
  - "hour_cos"
  # - "minute_sin"
  # - "minute_cos"

# optimizer
optimizer:
  lr: 0.0005

# scheduler
scheduler:
  num_warmup_steps: 0